services:
  db:
    image: postgres:15-alpine
    container_name: traveloop-db
    restart: always
    environment:
      POSTGRES_USER: traveloop_user
      POSTGRES_PASSWORD: traveloop_password
      POSTGRES_DB: traveloop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
