import React, { useEffect, useState, useCallback } from 'react';
import {
  StyleSheet, View, Text, TouchableOpacity, SafeAreaView, ScrollView,
  ActivityIndicator, Alert, Share, TextInput, Modal
} from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { ArrowLeft, Search, SlidersHorizontal, ChevronDown, Download, Share2, CheckCircle, FileText, DollarSign, Plus, Trash2 } from 'lucide-react-native';
import { useAuth } from '@/src/context/AuthContext';
import { apiRequest } from '@/src/api/client';

export default function InvoiceScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const { token } = useAuth();
  const router = useRouter();
  const [trip, setTrip] = useState<any>(null);
  const [budget, setBudget] = useState<any>(null);
  const [activities, setActivities] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [paid, setPaid] = useState(false);
  const [search, setSearch] = useState('');

  const fetchData = useCallback(async () => {
    const [tripRes, budgetRes] = await Promise.all([
      apiRequest(`/trips/${id}`, 'GET', undefined, token),
      apiRequest(`/trips/${id}/budget`, 'GET', undefined, token),
    ]);
    if (tripRes.success) {
      const t = tripRes.data as any;
      setTrip(t);
      const acts: any[] = [];
      t.stops?.forEach((stop: any) => stop.activities?.forEach((act: any) => acts.push({ ...act, city: stop.city?.name })));
      setActivities(acts);
    }
    if (budgetRes.success) setBudget(budgetRes.data);
    setLoading(false);
  }, [id, token]);

  useEffect(() => { fetchData(); }, [fetchData]);

  if (loading) return <SafeAreaView style={s.safe}><ActivityIndicator size="large" color="#00696b" style={{ flex: 1 }} /></SafeAreaView>;
  if (!trip) return null;

  const invoiceId = `INV-TL-${id.slice(0, 8).toUpperCase()}`;
  const generatedDate = new Date().toLocaleDateString('en', { month: 'long', day: 'numeric', year: 'numeric' });

  const filtered = activities.filter(a => a.title.toLowerCase().includes(search.toLowerCase()));
  const subtotal = filtered.reduce((s, a) => s + (a.cost || 0), 0);
  const tax = subtotal * 0.05;
  const discount = 50;
  const grand = subtotal + tax - discount;

  const handleMarkPaid = () => {
    const next = !paid;
    setPaid(next);
    Alert.alert(next ? 'Marked as Paid ✓' : 'Marked as Pending', next ? 'This invoice has been marked as paid.' : 'Invoice reverted to pending.');
  };

  const handleDownload = async () => {
    const lines = [
      `TRAVELOOP EXPENSE INVOICE`,
      `Invoice ID: ${invoiceId}`,
      `Trip: ${trip.title}`,
      `Generated: ${generatedDate}`,
      `Status: ${paid ? 'PAID' : 'PENDING'}`,
      ``,
      `ITEMS:`,
      ...filtered.map((a, i) => `${i + 1}. ${a.title}${a.city ? ` (${a.city})` : ''} — $${a.cost || 0}`),
      ``,
      `Subtotal: $${subtotal.toFixed(2)}`,
      `Tax (5%): $${tax.toFixed(2)}`,
      `Discount: -$${discount.toFixed(2)}`,
      `GRAND TOTAL: $${grand.toFixed(2)}`,
    ].join('\n');
    try { await Share.share({ message: lines, title: `Invoice ${invoiceId}` }); }
    catch { Alert.alert('Invoice Ready', `Invoice ${invoiceId} downloaded.`); }
  };

  const handleExportPDF = async () => {
    const lines = [
      `📄 TRAVELOOP INVOICE — ${invoiceId}`,
      `═══════════════════════════════`,
      `Trip: ${trip.title}`,
      `Date: ${generatedDate}`,
      `Status: ${paid ? '✅ PAID' : '⏳ PENDING'}`,
      ``,
      `TRAVELER DETAILS`,
      `────────────────`,
      `${trip.userId?.slice(0, 8) || 'James • Arjun • Jerry • Cristina'}`,
      ``,
      `EXPENSE BREAKDOWN`,
      `────────────────`,
      ...filtered.map((a, i) => `${i + 1}. ${a.title}${a.city ? ` | ${a.city}` : ''} — USD $${(a.cost || 0).toFixed(2)}`),
      ``,
      `SUMMARY`,
      `────────────────`,
      `Subtotal:    $${subtotal.toFixed(2)}`,
      `Tax (5%):    $${tax.toFixed(2)}`,
      `Discount:   -$${discount.toFixed(2)}`,
      `TOTAL:       $${grand.toFixed(2)}`,
      ``,
      `Generated by Traveloop • traveloop.app`,
    ].join('\n');
    try { await Share.share({ message: lines, title: `Invoice ${invoiceId} — PDF Export` }); }
    catch { Alert.alert('PDF Exported', `Invoice ${invoiceId} ready to share.`); }
  };

  return (
    <SafeAreaView style={s.safe}>
      <View style={s.headerRow}>
        <TouchableOpacity onPress={() => router.back()} style={s.backBtn}>
          <ArrowLeft color="#191c1e" size={20} />
        </TouchableOpacity>
        <View style={{ flex: 1, marginLeft: 12 }}>
          <Text style={s.brand}>Invoice</Text>
        </View>
      </View>

      <ScrollView style={s.scroll} contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
        {/* Invoice Header Card */}
        <View style={s.invoiceCard}>
          <View style={s.invoiceTop}>
            <View>
              <Text style={s.invoiceTitle}>Expense Invoice</Text>
              <Text style={s.invoiceId}>{invoiceId}</Text>
            </View>
            <View style={[s.payStatus, paid && s.payStatusPaid]}>
              <Text style={[s.payStatusText, paid && s.payStatusTextPaid]}>{paid ? '✓ PAID' : 'PENDING'}</Text>
            </View>
          </View>

          <View style={s.divider} />

          <Text style={s.tripName}>{trip.title}</Text>
          <View style={s.invoiceMeta}>
            <Text style={s.invoiceMetaText}>Generated: {generatedDate}</Text>
            <Text style={s.invoiceMetaText}>Payment status — {paid ? 'paid' : 'pending'}</Text>
          </View>

          {/* Traveler details */}
          <View style={s.travelerSection}>
            <Text style={s.travelerLabel}>Traveler Details:</Text>
            <Text style={s.travelerName}>{trip.userId?.slice(0, 8) || 'James • Arjun • Jerry • Cristina'}</Text>
          </View>
        </View>

        {/* Search */}
        <View style={s.searchWrap}>
          <Search color="#75777e" size={20} style={{ marginRight: 12 }} />
          <TextInput style={s.searchInput} value={search} onChangeText={setSearch} placeholder="Search invoice items..." placeholderTextColor="#75777e" />
        </View>

        {/* Controls */}
        <View style={s.controls}>
          <TouchableOpacity style={s.controlChip}><Text style={s.controlText}>Group by</Text><ChevronDown color="#75777e" size={14} /></TouchableOpacity>
          <TouchableOpacity style={s.controlChip}><SlidersHorizontal color="#75777e" size={14} /><Text style={s.controlText}>Filter</Text></TouchableOpacity>
        </View>

        {/* Items Table */}
        <View style={s.table}>
          {/* Table Header */}
          <View style={s.tableHeader}>
            <Text style={[s.th, { width: 28 }]}>#</Text>
            <Text style={[s.th, { flex: 1 }]}>Description</Text>
            <Text style={[s.th, { width: 80 }]}>Category</Text>
            <Text style={[s.th, { width: 70, textAlign: 'right' }]}>Unit Cost</Text>
          </View>

          {/* Table Rows */}
          {filtered.length === 0 && (
            <View style={s.emptyTable}>
              <Text style={s.emptyTableText}>No expense items yet. Add activities with costs to city stops.</Text>
            </View>
          )}
          {filtered.map((act, idx) => (
            <View key={act.id} style={[s.tableRow, idx % 2 === 1 && s.tableRowAlt]}>
              <Text style={[s.td, { width: 28, fontWeight: '600' }]}>{idx + 1}</Text>
              <View style={{ flex: 1 }}>
                <Text style={s.tdMain} numberOfLines={1}>{act.title}</Text>
                {act.city && <Text style={s.tdSub}>{act.city}</Text>}
              </View>
              <Text style={[s.td, { width: 80 }]}>travel</Text>
              <Text style={[s.td, { width: 70, textAlign: 'right', color: '#00696b', fontWeight: '700' }]}>
                {act.cost > 0 ? `$${act.cost}` : '–'}
              </Text>
            </View>
          ))}
        </View>

        {/* Totals */}
        <View style={s.totalsCard}>
          <View style={s.totalRow}>
            <Text style={s.totalLabel}>Subtotal...</Text>
            <Text style={s.totalValue}>${subtotal.toFixed(2)}</Text>
          </View>
          <View style={s.totalRow}>
            <Text style={s.totalLabel}>Tax (5%)</Text>
            <Text style={s.totalValue}>${tax.toFixed(2)}</Text>
          </View>
          <View style={s.totalRow}>
            <Text style={s.totalLabel}>Discount</Text>
            <Text style={[s.totalValue, { color: '#00696b' }]}>-${discount.toFixed(2)}</Text>
          </View>
          <View style={s.divider} />
          <View style={s.totalRow}>
            <Text style={s.grandLabel}>Grand Total</Text>
            <Text style={s.grandValue}>${grand.toFixed(2)}</Text>
          </View>
        </View>

        {/* Budget Insights banner */}
        {budget && (
          <View style={s.insightCard}>
            <DollarSign color="#ba1a1a" size={24} />
            <View style={{ flex: 1, marginLeft: 16 }}>
              <Text style={s.insightTitle}>Budget Insights</Text>
              <Text style={s.insightText}>
                Total Budget: ${budget.totalLimit} · Total spent: ${budget.spent} · Remaining: ${(budget.totalLimit - budget.spent).toFixed(0)}
              </Text>
            </View>
          </View>
        )}

        {/* Action Buttons */}
        <View style={s.actions}>
          <TouchableOpacity
            style={[s.actionBtn, paid && s.actionBtnPaid]}
            onPress={handleMarkPaid}
            activeOpacity={0.8}
          >
            <CheckCircle color={paid ? '#00696b' : '#75777e'} size={20} />
            <Text style={[s.actionBtnText, paid && { color: '#00696b' }]}>{paid ? '✓ Paid — Tap to revert' : 'Mark as Paid'}</Text>
          </TouchableOpacity>

          <TouchableOpacity style={s.actionBtn} onPress={handleDownload} activeOpacity={0.8}>
            <Download color="#191c1e" size={20} />
            <Text style={s.actionBtnText}>Download Invoice</Text>
          </TouchableOpacity>

          <TouchableOpacity style={[s.actionBtn, { backgroundColor: '#00696b', borderColor: '#00696b' }]} onPress={handleExportPDF} activeOpacity={0.8}>
            <Share2 color="#FFF" size={20} />
            <Text style={[s.actionBtnText, { color: '#FFF' }]}>Export as PDF</Text>
          </TouchableOpacity>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#f7f9fb' },
  scroll: { flex: 1 },
  content: { padding: 20, paddingBottom: 80 },
  headerRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20, paddingTop: 10, paddingBottom: 10, backgroundColor: '#f7f9fb' },
  backBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#ffffff', justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: '#eceef0', shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 4, elevation: 2, marginRight: 12 },
  brand: { fontSize: 20, fontWeight: '700', color: '#191c1e' },
  invoiceCard: { backgroundColor: '#ffffff', borderRadius: 24, padding: 24, marginBottom: 20, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 8, elevation: 3 },
  invoiceTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 16 },
  invoiceTitle: { fontSize: 24, fontWeight: '800', color: '#191c1e', marginBottom: 4, letterSpacing: -0.5 },
  invoiceId: { fontSize: 14, color: '#00696b', fontWeight: '600', fontFamily: 'monospace' },
  payStatus: { backgroundColor: '#ffdad6', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, borderWidth: 1, borderColor: '#ba1a1a' },
  payStatusPaid: { backgroundColor: '#e6f4ea', borderColor: '#34D399' },
  payStatusText: { fontSize: 12, fontWeight: '800', color: '#ba1a1a', letterSpacing: 0.5 },
  payStatusTextPaid: { color: '#0d652d' },
  divider: { height: 1, backgroundColor: '#eceef0', marginVertical: 16 },
  tripName: { fontSize: 18, fontWeight: '700', color: '#191c1e', marginBottom: 6 },
  invoiceMeta: { gap: 6, marginBottom: 16 },
  invoiceMetaText: { fontSize: 14, color: '#44474d' },
  travelerSection: { backgroundColor: '#f2f4f6', borderRadius: 16, padding: 16 },
  travelerLabel: { fontSize: 12, color: '#75777e', fontWeight: '600', marginBottom: 6, textTransform: 'uppercase' },
  travelerName: { fontSize: 15, color: '#191c1e', fontWeight: '500' },
  searchWrap: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#eceef0', borderRadius: 12, paddingHorizontal: 16, paddingVertical: 12, marginBottom: 16 },
  searchInput: { flex: 1, color: '#191c1e', fontSize: 16 },
  controls: { flexDirection: 'row', gap: 8, marginBottom: 20 },
  controlChip: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#ffffff', borderRadius: 20, paddingHorizontal: 14, paddingVertical: 8, borderWidth: 1, borderColor: '#eceef0' },
  controlText: { color: '#44474d', fontSize: 13, fontWeight: '600' },
  table: { backgroundColor: '#ffffff', borderRadius: 20, overflow: 'hidden', marginBottom: 20, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 8, elevation: 2 },
  tableHeader: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 14, backgroundColor: '#f2f4f6', borderBottomWidth: 1, borderBottomColor: '#eceef0' },
  th: { fontSize: 12, fontWeight: '700', color: '#75777e', textTransform: 'uppercase', letterSpacing: 0.5 },
  emptyTable: { padding: 32, alignItems: 'center' },
  emptyTableText: { fontSize: 14, color: '#75777e', textAlign: 'center' },
  tableRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 14 },
  tableRowAlt: { backgroundColor: '#f7f9fb' },
  td: { fontSize: 14, color: '#44474d' },
  tdMain: { fontSize: 15, color: '#191c1e', fontWeight: '600' },
  tdSub: { fontSize: 12, color: '#75777e', marginTop: 2 },
  totalsCard: { backgroundColor: '#ffffff', borderRadius: 20, padding: 20, marginBottom: 20, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 8, elevation: 2 },
  totalRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  totalLabel: { fontSize: 15, color: '#44474d' },
  totalValue: { fontSize: 15, color: '#191c1e', fontWeight: '600' },
  grandLabel: { fontSize: 18, fontWeight: '800', color: '#191c1e' },
  grandValue: { fontSize: 24, fontWeight: '900', color: '#00696b' },
  insightCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#ffdad6', borderRadius: 16, padding: 16, marginBottom: 24, borderWidth: 1, borderColor: '#ba1a1a' },
  insightTitle: { fontSize: 14, fontWeight: '700', color: '#ba1a1a', marginBottom: 4 },
  insightText: { fontSize: 13, color: '#900b09', lineHeight: 18 },
  actions: { gap: 12 },
  actionBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, backgroundColor: '#ffffff', borderRadius: 16, padding: 16, borderWidth: 1, borderColor: '#eceef0', shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 4, elevation: 1 },
  actionBtnPaid: { backgroundColor: '#e6f4ea', borderColor: '#34D399' },
  actionBtnText: { color: '#191c1e', fontWeight: '700', fontSize: 15 },
});
